### ISSUE TITLE
Update to 0.9.30

### ISSUE THREAD

**Issue by gau-nernst** [conda-forge/lmdb-feedstock#21]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Update to 0.9.30 version

https://git.openldap.org/openldap/openldap/-/tree/LMDB_0.9.30

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by jjerphan** [comment]
The `LMDB_0.9.30` tag has not yet been pushed on LMDB's GitHub repository yet (see [its tags](https://github.com/LMDB/lmdb/tags)).

Once it is published, we can easily update to this version.

**Comment by h-vetinari** [comment]
Fixed in #25
