### ISSUE TITLE
Redistribute older versions of LMDB for Windows

### ISSUE THREAD

**Issue by jjerphan** [conda-forge/lmdb-feedstock#23]
### Comment:

Hello,

Thank you for maintaining this feedstock.

Maintainers of ArcticDB would like to distribute it for Windows on conda-forge (addressed by https://github.com/conda-forge/arcticdb-feedstock/pull/1#issuecomment-1563607297). It is currently not distributed because LMDB is not distributed on Windows (addressed by #22).

[ArcticDB currently depends on a previous version of LMDB: 0.9.22](https://github.com/conda-forge/arcticdb-feedstock/blob/main/recipe/meta.yaml#L55).

If #22 were to be accepted, would it be possible to distribute LMDB 0.9.22 for Windows ([using another branch on this feedstock](https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions))?

**Comment by rmax** [comment]
@conda-forge/core thoughts?

**Comment by hmaarrfk** [comment]
You can create a branch in the feedstock and maintain it with an older version.

To get the bot's help, you should configure the `conda-forge.yml` 

One example:

https://github.com/conda-forge/qt-main-feedstock/blob/main/conda-forge.yml#L7

The little documentation I found: https://conda-forge.org/docs/maintainer/conda_forge_yml.html#bot

**Comment by jjerphan** [comment]
I am willing to co-maintain this feedstock to help packaging this version. What do you think?

**Comment by jjerphan** [comment]
Closing this issue as not planned as discussed in https://github.com/conda-forge/lmdb-feedstock/pull/24.
