### ISSUE TITLE
Borked build number for 0.9.22

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/lmdb-feedstock#26]
@jjerphan, immediately after you gained maintenance rights here, you pushed a maintenance branch (without discussion and at the wrong point in history), then published a new build of 0.9.22 (without a PR; 486095133fe93336d7c0d9184d923085dfe8054f), and consequently messed up the build numbers, because there are existing 0.9.22 [builds](https://anaconda.org/conda-forge/lmdb/files) with build number `_1000`, and so the "new" builds with `_0` will always be subordinate to that.

The third point I'll count as an oversight, but the first two are pretty bad violations of maintenance policy, and look especially bad if you've just joined a feedstock. Don't do that again.

**Comment by jjerphan** [comment]
Yes, this is a significantly bad mistake I uncomfortably did when ArcticDB was being released in a rush.

I do not want to be doing this ever again.
